[tool.poetry]
name = "airbnb"
version = "0.1.0"
description = ""
authors = ["뮨 <Sevencat82@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
